name: recsys-dev
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy>=1.22.0
    - pandas>=1.3.5
    - nltk>=3.6.7
    - scipy>=1.7.3
    - scikit-learn>=1.0.2
    - beautifulsoup4>=4.10.0
    - unidecode>=1.3.2
    - requests>=2.26.0